### PR TITLE
fix: Only request vendorlist once

### LINKED ISSUE #206: vendorlist is called multiple times
It seems that there is a bug/racecondition, when you load several ads on page load. 

When a page loads one ad, and on scroll triggers a new, then we only see one request to the vendorlist.

But when we load more then one ad on page load, we see one request pr ad. 

image
image

This can be seen at https://www.seher.no/kjendis/ikke-min-skyld-at-ben-affleck-er-pa-rehab/70168240 on a medium size monitor.

### PR DESCRIPTION
**Pull request by Fumler**
Fixes #206 

This PR sets a flag whenever you do a request for the vendorlist, so if there is several calls to `loadVendorList()` before the request is resolved and cache is saved, we wait for the first request to resolve in the other calls.

### CODE REVIEW

**Comment by Fumler** [comment]
Does not seem like your test coverage works properly? The coverage report basically say everything in `oil.bundle.js` is red, so the 27% coverage is just variables etc?

I don't know how to fix this. Maybe one of you guys know where to start? 😅

File: src/scripts/core/core_vendor_information.js [hunk 1]
```diff
@@ -10,12 +10,35 @@ export const DEFAULT_VENDOR_LIST = {
...
 export let cachedVendorList;
+export let startedVendorlistRequest = false;
 
 export function loadVendorList() {
   return new Promise(function (resolve) {
     if (cachedVendorList) {
+      // if we have cached vendorlist, return that
       resolve(cachedVendorList);
+    } else if (startedVendorlistRequest) {
+      // if a request for the vendorlist has been started, let's wait for it
```
Comment (phogel) [inline src/scripts/core/core_vendor_information.js]: Wouldn't it be simpler to just store the pending Promise in a variable named
`pendingVendorlistPromise` in line 41?
Return it in line 22 if it exists.
Nullify pendingVendorlistPromise when the result of fetchJsonData(iabVendorListUrl) is there and cachedVendorList is set.
The test for a timeout you could move inside the else block then.

**Comment by phogel** [comment]
To be honest, I am not sure how exactly coveralls gets to this result. I'd say a decrease of "0.06%" is neglectable.

File: src/scripts/core/core_vendor_information.js (hunk 1 above)
Comment (phogel) [reply src/scripts/core/core_vendor_information.js]: Also a test for the timeout would be great! 👍

**Comment by Fumler** [comment]
Any updates on this?

**Comment by Fumler** [comment]
Sorry for nagging, but we really want this released. Does anyone have time to CR and merge this or should we start using a fork?

@ltparis2018 @tbtz @phogel

**Comment by marcelb** [comment]
@Fumler Heya, I'm back in the team and will look into this today!

File: src/scripts/core/core_vendor_information.js [hunk 2]
```diff
@@ -10,20 +10,25 @@ export const DEFAULT_VENDOR_LIST = {
...
 
 export let cachedVendorList;
+export let pendingVendorlistPromise = null;
 
 export function loadVendorList() {
   return new Promise(function (resolve) {
     if (cachedVendorList) {
       resolve(cachedVendorList);
+    } else if (pendingVendorlistPromise) {
+      return pendingVendorlistPromise;
```
Comment (marcelb) [inline src/scripts/core/core_vendor_information.js]: Please add a test to check if this works correctly. I think this doesn't return function loadVendorList() but the inner anonymous function (resolve) {} unresolved instead. I would expect unexpected behavior where loadVendorList() is used. I think you want to return an unnested promise instead that behaves exactly like all the others.

Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: I would probably refactor the whole function that not the whole scope is inside that huge Promise return.

File: test/specs/core/core_vendor_information.spec.js [hunk 3]
```diff
@@ -52,6 +52,18 @@ describe('core_vendor_information', () => {
       });
     });
 
+    it('should wait for cached vendor list if request is already started', (done) => {
+      let fetchSpy = spyOn(CoreUtils, 'fetchJsonData').and.returnValue(new Promise((resolve) => resolve(VENDOR_LIST)));
+      spyOn(CoreConfig, 'getIabVendorListUrl').and.returnValue("https://iab.vendor.list.url");
+
+      loadVendorList().then(() => {});
+      loadVendorList().then(() => {});
```
Comment (marcelb) [inline test/specs/core/core_vendor_information.spec.js]: Please make also sure that the second loadVendorList().then() is called before the the first resolves. I'm not sure whether the second to fourth call is not just returning the cached version and this couldn't have racing conditions. If you are please explain.

File: src/scripts/core/core_vendor_information.js (hunk 2 above)
Comment (Fumler) [reply src/scripts/core/core_vendor_information.js]: I'm not sure what you mean. The idea is: 
- On the first call to `loadVendorList` we return a promise, that when finished, will resolve to the vendorlist data.
- On the second call to `loadVendorList` we also return a promise, that when finished, will resolve to the vendorlist data, as long as there is no cached version, and we have already started a promise
- On the third call to `loadVendorList` we also return a promise, that when finished, will resolve to the vendorlist data, as long as there is no cached version, and we have already started a promise
- .. etc

The second and third cases will only return the started promise if it exists.

File: test/specs/core/core_vendor_information.spec.js (hunk 3 above)
Comment (Fumler) [reply test/specs/core/core_vendor_information.spec.js]: I updated the tests.

File: src/scripts/core/core_vendor_information.js (hunk 2 above)
Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: "- On the second call to loadVendorList we also return a promise, that when finished, will resolve to the vendorlist data, as long as there is no cached version, and we have already started a promise"

Thats the one im not sure that it works as intended. There is a return statement returning the promise inside another promise (line 16). Not resolving, returning. (line 19)

Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: But anyway, the tests are looking fine and should fail, if its actually broken. Thank you!
The change has a lot of sense, thank you for the contribution and sorry for the long delay!

Im not entirely sure yet though and can't create a new version today anymore and will be on a 1 day vacation tomorrow.  @ltparis2018 @tbtz Can you have a look as well and merge it tomorrow? If not I'll be back on monday and finish this up. Thanks!

Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: im on it again :) I think we will be merging it soon, but we might do a small refactoring on it later.

Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: @Fumler I did some tests on the code and I believe its still broken.

The test can't catch the errors though, because its also flawed. The tests done() function is executed before the Promises can resolve, so all the expects within this test wont run at all.
A quick fix is to move the done() in the last async method, which results in a failed test (because the last loadVendorList() never resolves).

There are two bugs within the function. One being returning the pendingVendorlistPromise instead of resolving it and the second one is the call to fetchJsonData which doesn't set the pendingVendorlistPromise variable probably. It resolves the right side first, resulting in a wrong value in the variable.

The test also assumes implicit timings of the code to work, which seems to be ok though, not raising any race conditions. 

Please fix those remaining issues.

Comment (marcelb) [reply src/scripts/core/core_vendor_information.js]: This line should rather read 
resolve(pendingVendorlistPromise);

This of course results in nested Promises, which works.

File: src/scripts/core/core_vendor_information.js [hunk 4]
```diff
@@ -10,20 +10,25 @@ export const DEFAULT_VENDOR_LIST = {
...
     } else {
       let iabVendorListUrl = getIabVendorListUrl();
-      fetchJsonData(iabVendorListUrl)
+      pendingVendorlistPromise = fetchJsonData(iabVendorListUrl)
```
Comment (marcelb) [inline src/scripts/core/core_vendor_information.js]: This should rather read

pendingVendorlistPromise = fetchJsonData(iabVendorListUrl)
      pendingVendorlistPromise.then(response => {

to assign the right value to pendingVendorListPromise

File: test/specs/core/core_vendor_information.spec.js [hunk 5]
```diff
@@ -52,6 +54,33 @@ describe('core_vendor_information', () => {
...
+        expect(retrievedVendorList).toEqual(VENDOR_LIST);
+      });
+      expect(cachedVendorList).toBeUndefined();
+      loadVendorList().then((retrievedVendorList) => {
+        expect(retrievedVendorList.vendorListVersion).toEqual(VENDOR_LIST.vendorListVersion);
+        expect(retrievedVendorList).toEqual(VENDOR_LIST);
+      });
+      expect(fetchSpy.calls.count()).toBe(1);
+
+      done();
```
Comment (marcelb) [inline test/specs/core/core_vendor_information.spec.js]: This done() should be on line 77 instead to make the test work.

Comment (Fumler) [reply test/specs/core/core_vendor_information.spec.js]: Good catch!

**Comment by marcelb** [comment]
Thanks! This is merged and we will create a new release as well soon.
